name: Keep Render App Awake

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render App
        run: curl -s -o /dev/null -w "%{http_code}" https://insyd-04ii.onrender.com/health
